In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [10]:
df=pd.read_csv(r'E:\code\AI study\ML\code\3) Feature engineering\covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

### city,gender -- one hot encoding
### cough -- ordinal encoding
### fever (has missing values)
### has_covid -- lable encoder
### we are not doing scaling today

In [11]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(df.drop(columns=['has_covid']),
                                           df['has_covid'],
                                           test_size=0.2
                                           )

xtrain

    age  gender  fever   cough       city
64   42    Male  104.0    Mild     Mumbai
71   75  Female  104.0  Strong      Delhi
23   80  Female   98.0    Mild      Delhi
32   34  Female  101.0  Strong      Delhi
40   49  Female  102.0    Mild      Delhi
..  ...     ...    ...     ...        ...
72   83  Female  101.0    Mild    Kolkata
68   54  Female  104.0  Strong    Kolkata
78   11    Male  100.0    Mild  Bangalore
49   44    Male  104.0    Mild     Mumbai
22   71  Female   98.0  Strong    Kolkata

[80 rows x 5 columns]

In [12]:
ytrain

64     No
71     No
23    Yes
32    Yes
40     No
     ...
72     No
68     No
78    Yes
49     No
22    Yes
Name: has_covid, Length: 80, dtype: str

In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [18]:
from sklearn.compose import ColumnTransformer

transformer=ColumnTransformer(transformers=[
                               ('tnf1',SimpleImputer(),['fever']),
                               ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                               ('tnf3',OneHotEncoder(drop='first',sparse_output=False),['city','gender'])
                              ],
                              remainder ='passthrough')

In [24]:
transformer.fit_transform(xtrain).shape

(80, 7)

In [25]:
transformer.transform(xtest).shape

(20, 7)