In [99]:
import numpy as np
import pandas as pd

In [100]:
data=pd.read_csv('play_tennis.csv')
data.head()
data.drop(columns=['day'],inplace=True)
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [101]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [102]:
py=9/14
pn=5/14
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [103]:
pd.crosstab(data['outlook'],data['play'],margins=True,normalize='columns')

play       No       Yes       All
outlook
Overcast  0.0  0.444444  0.285714
Rain      0.4  0.333333  0.357143
Sunny     0.6  0.222222  0.357143

In [104]:
pd.crosstab(data['temp'],data['play'],margins=True,normalize='columns')

play   No       Yes       All
temp
Cool  0.2  0.333333  0.285714
Hot   0.4  0.222222  0.285714
Mild  0.4  0.444444  0.428571

In [105]:
X=data[['outlook','temp','humidity','wind']]
y=data['play']

In [106]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [107]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2
)

In [108]:

model = GaussianNB()
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'Sunny'

In [ ]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

NameError: name 'model' is not defined